/**
 * breakdown-sched-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Scene model module.
 * @module model/Scene
 * @version 0.1.0
 */
class Scene {
    /**
     * Constructs a new <code>Scene</code>.
     * @alias module:model/Scene
     * @param episode {String} 
     * @param sceneNumber {String} 
     * @param setting {String} 
     * @param slug {String} 
     * @param timeOfDay {String} 
     * @param scriptDay {String} 
     */
    constructor(episode, sceneNumber, setting, slug, timeOfDay, scriptDay) { 
        
        Scene.initialize(this, episode, sceneNumber, setting, slug, timeOfDay, scriptDay);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, episode, sceneNumber, setting, slug, timeOfDay, scriptDay) { 
        obj['episode'] = episode;
        obj['sceneNumber'] = sceneNumber;
        obj['setting'] = setting;
        obj['slug'] = slug;
        obj['timeOfDay'] = timeOfDay;
        obj['scriptDay'] = scriptDay;
    }

    /**
     * Constructs a <code>Scene</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Scene} obj Optional instance to populate.
     * @return {module:model/Scene} The populated <code>Scene</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Scene();

            if (data.hasOwnProperty('episode')) {
                obj['episode'] = ApiClient.convertToType(data['episode'], 'String');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = ApiClient.convertToType(data['location'], 'String');
            }
            if (data.hasOwnProperty('sceneNumber')) {
                obj['sceneNumber'] = ApiClient.convertToType(data['sceneNumber'], 'String');
            }
            if (data.hasOwnProperty('setting')) {
                obj['setting'] = ApiClient.convertToType(data['setting'], 'String');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('timeOfDay')) {
                obj['timeOfDay'] = ApiClient.convertToType(data['timeOfDay'], 'String');
            }
            if (data.hasOwnProperty('scriptDay')) {
                obj['scriptDay'] = ApiClient.convertToType(data['scriptDay'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} episode
 */
Scene.prototype['episode'] = undefined;

/**
 * @member {String} location
 */
Scene.prototype['location'] = undefined;

/**
 * @member {String} sceneNumber
 */
Scene.prototype['sceneNumber'] = undefined;

/**
 * @member {String} setting
 */
Scene.prototype['setting'] = undefined;

/**
 * @member {String} slug
 */
Scene.prototype['slug'] = undefined;

/**
 * @member {String} timeOfDay
 */
Scene.prototype['timeOfDay'] = undefined;

/**
 * @member {String} scriptDay
 */
Scene.prototype['scriptDay'] = undefined;






export default Scene;

