/**
 * breakdown-sched-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BreakdownSchedSdk);
  }
}(this, function(expect, BreakdownSchedSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BreakdownSchedSdk.Scene();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Scene', function() {
    it('should create an instance of Scene', function() {
      // uncomment below and update the code to test Scene
      //var instane = new BreakdownSchedSdk.Scene();
      //expect(instance).to.be.a(BreakdownSchedSdk.Scene);
    });

    it('should have the property episode (base name: "episode")', function() {
      // uncomment below and update the code to test the property episode
      //var instane = new BreakdownSchedSdk.Scene();
      //expect(instance).to.be();
    });

    it('should have the property location (base name: "location")', function() {
      // uncomment below and update the code to test the property location
      //var instane = new BreakdownSchedSdk.Scene();
      //expect(instance).to.be();
    });

    it('should have the property sceneNumber (base name: "sceneNumber")', function() {
      // uncomment below and update the code to test the property sceneNumber
      //var instane = new BreakdownSchedSdk.Scene();
      //expect(instance).to.be();
    });

    it('should have the property setting (base name: "setting")', function() {
      // uncomment below and update the code to test the property setting
      //var instane = new BreakdownSchedSdk.Scene();
      //expect(instance).to.be();
    });

    it('should have the property slug (base name: "slug")', function() {
      // uncomment below and update the code to test the property slug
      //var instane = new BreakdownSchedSdk.Scene();
      //expect(instance).to.be();
    });

    it('should have the property timeOfDay (base name: "timeOfDay")', function() {
      // uncomment below and update the code to test the property timeOfDay
      //var instane = new BreakdownSchedSdk.Scene();
      //expect(instance).to.be();
    });

    it('should have the property scriptDay (base name: "scriptDay")', function() {
      // uncomment below and update the code to test the property scriptDay
      //var instane = new BreakdownSchedSdk.Scene();
      //expect(instance).to.be();
    });

  });

}));
